# Generated by Django 4.2.28 on 2026-02-21 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_tables', '0001_initial'),
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('users', models.ManyToManyField(blank=True, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.BigIntegerField()),
                ('dv', models.IntegerField(blank=True, null=True)),
                ('legal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_lastname', models.CharField(blank=True, max_length=255, null=True)),
                ('second_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colombian_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='reference_tables.colombiancity')),
                ('colombian_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='reference_tables.colombiandepartment')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='accounting.country')),
                ('dian_economic_activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='reference_tables.dianeconomicactivity')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='reference_tables.documenttype')),
            ],
            options={
                'db_table': 'companies',
                'unique_together': {('document_type', 'document_number')},
            },
        ),
    ]
