# Generated by Django 6.0.2 on 2026-02-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_method_orders',
            },
        ),
        migrations.CreateModel(
            name='SaleTypeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sale_type_orders',
            },
        ),
    ]
