# Generated by Django 4.2.28 on 2026-02-21 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_tables', '0001_initial'),
        ('accounting', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='third_parties', to='core.company'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='third_parties', to='accounting.country'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='dian_economic_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_parties', to='reference_tables.dianeconomicactivity'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='third_parties', to='reference_tables.documenttype'),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_prices', to='core.company'),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='accounting.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.company'),
        ),
        migrations.AddField(
            model_name='item',
            name='excise_tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reference_tables.excisetaxrate'),
        ),
        migrations.AddField(
            model_name='item',
            name='excise_tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reference_tables.excisetaxtype'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounting.itemgroup'),
        ),
        migrations.AddField(
            model_name='item',
            name='iva_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reference_tables.ivarate'),
        ),
        migrations.AddField(
            model_name='item',
            name='iva_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reference_tables.ivatype'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='reference_tables.unitmeasure'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('code', 'company')},
        ),
    ]
