# Generated by Django 6.0.2 on 2026-02-24 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
    ]
