# Generated by Django 6.0.2 on 2026-02-24 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20260224_0113'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Yes/No'), ('date', 'Date'), ('choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'item_property_types',
            },
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('company', 'code')},
        ),
        migrations.AddField(
            model_name='item',
            name='base_code',
            field=models.CharField(default='DEFAULT', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='base_name',
            field=models.CharField(default='Default Item', max_length=255),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_variant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='parent_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accounting.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='variant_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ItemPropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_values', to='accounting.itempropertytype')),
            ],
            options={
                'db_table': 'item_property_values',
                'unique_together': {('property_type', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('purchase', 'Purchase Order'), ('sale', 'Sale Order'), ('quote', 'Quote')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_excise_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.company')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounting.thirdparty')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('item_properties', models.JSONField(blank=True, help_text='Item-specific properties like color, size, etc.', null=True)),
                ('line_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_excise_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('line_total_with_taxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='accounting.itemprice')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='accounting.order')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_value', models.CharField(blank=True, max_length=255, null=True)),
                ('number_value', models.IntegerField(blank=True, null=True)),
                ('decimal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('date_value', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounting.item')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.itempropertytype')),
                ('choice_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.itempropertyvalue')),
            ],
            options={
                'db_table': 'item_properties',
                'unique_together': {('item', 'property_type')},
            },
        ),
    ]
