# Generated by Django 6.0.2 on 2026-02-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_add_order_counter'),
        ('reference_tables', '0002_add_sale_type_and_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reference_tables.paymentmethodorder'),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reference_tables.saletypeorder'),
        ),
    ]
