# Generated by Django 6.0.2 on 2026-02-24 20:41

from django.db import migrations


def populate_order_reference_fields(apps, schema_editor):
    """Populate sale_type and payment_method for existing orders with default values"""
    Order = apps.get_model('accounting', 'Order')
    SaleTypeOrder = apps.get_model('reference_tables', 'SaleTypeOrder')
    PaymentMethodOrder = apps.get_model('reference_tables', 'PaymentMethodOrder')
    
    # Get default values (Presencial and Contraentrega)
    try:
        default_sale_type = SaleTypeOrder.objects.get(name='Presencial')
        default_payment_method = PaymentMethodOrder.objects.get(name='Contraentrega')
        
        # Update existing orders that don't have these fields populated
        Order.objects.filter(sale_type__isnull=True).update(sale_type=default_sale_type)
        Order.objects.filter(payment_method__isnull=True).update(payment_method=default_payment_method)
        
    except (SaleTypeOrder.DoesNotExist, PaymentMethodOrder.DoesNotExist):
        # If reference data doesn't exist, skip (should not happen if seeds were run)
        pass


def reverse_populate_order_reference_fields(apps, schema_editor):
    """Reverse operation - set fields back to null"""
    Order = apps.get_model('accounting', 'Order')
    Order.objects.all().update(sale_type=None, payment_method=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_add_sale_type_and_payment_method_to_order'),
        ('reference_tables', '0002_add_sale_type_and_payment_method'),
    ]

    operations = [
        migrations.RunPython(
            populate_order_reference_fields,
            reverse_populate_order_reference_fields
        ),
    ]
