# Generated by Django 6.0.2 on 2026-02-24 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_populate_order_reference_fields'),
        ('reference_tables', '0002_add_sale_type_and_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reference_tables.paymentmethodorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='sale_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='reference_tables.saletypeorder'),
        ),
    ]
