# Generated by Django 6.0.2 on 2026-02-25 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_order_payment_method_alter_order_sale_type'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itempropertyvalue',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itempropertytype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_property_types', to='core.company'),
        ),
        migrations.AddField(
            model_name='itempropertyvalue',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_property_values', to='core.company'),
        ),
        migrations.AlterField(
            model_name='itempropertytype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='itempropertytype',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='itempropertyvalue',
            unique_together={('property_type', 'value', 'company')},
        ),
    ]
