# Generated by Django 6.0.2 on 2026-05-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_itempropertyvalue_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempropertytype',
            name='name_es',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
