# Generated by Django 6.0.2 on 2026-05-12 16:41

import django.db.models.deletion
from django.db import migrations, models

DATA_TYPES = [
    ('text',            'Text',            'Texto'),
    ('number',          'Number',          'Número'),
    ('decimal',         'Decimal',         'Decimal'),
    ('boolean',         'Yes/No',          'Sí/No'),
    ('date',            'Date',            'Fecha'),
    ('choice',          'Single Choice',   'Selección única'),
    ('multiple_choice', 'Multiple Choice', 'Selección múltiple'),
]


def create_data_types_and_migrate(apps, schema_editor):
    ItemPropertyDataType = apps.get_model('accounting', 'ItemPropertyDataType')
    ItemPropertyType = apps.get_model('accounting', 'ItemPropertyType')

    # Create the data type records
    code_to_obj = {}
    for code, name, name_es in DATA_TYPES:
        obj, _ = ItemPropertyDataType.objects.get_or_create(
            code=code, defaults={'name': name, 'name_es': name_es}
        )
        code_to_obj[code] = obj

    # Point existing ItemPropertyType rows at the new FK
    for ipt in ItemPropertyType.objects.all():
        old_code = ipt.data_type_old
        if old_code and old_code in code_to_obj:
            ipt.data_type = code_to_obj[old_code]
            ipt.save()


def reverse_migration(apps, schema_editor):
    ItemPropertyType = apps.get_model('accounting', 'ItemPropertyType')
    for ipt in ItemPropertyType.objects.select_related('data_type').all():
        if ipt.data_type:
            ipt.data_type_old = ipt.data_type.code
            ipt.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_add_name_es_to_item_property_type'),
    ]

    operations = [
        # 1. Create the new lookup table
        migrations.CreateModel(
            name='ItemPropertyDataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'item_property_data_types',
                'ordering': ['name'],
            },
        ),
        # 2. Remove name_es from ItemPropertyType (added in 0010)
        migrations.RemoveField(
            model_name='itempropertytype',
            name='name_es',
        ),
        # 3. Rename old CharField to data_type_old so we can read it during data migration
        migrations.RenameField(
            model_name='itempropertytype',
            old_name='data_type',
            new_name='data_type_old',
        ),
        # 4. Add the new FK column (nullable)
        migrations.AddField(
            model_name='itempropertytype',
            name='data_type',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='property_types',
                to='accounting.itempropertydatatype',
            ),
        ),
        # 5. Populate FK from old CharField values
        migrations.RunPython(create_data_types_and_migrate, reverse_migration),
        # 6. Drop the old CharField
        migrations.RemoveField(
            model_name='itempropertytype',
            name='data_type_old',
        ),
    ]
